AWSTemplateFormatVersion: "2012-10-17"
Resources:
  S3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: njita-static-website-bucket
      AccessControl: PublicRead
      WebsiteConfiguration:
        IndexDocument: index.html
  BucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref S3Bucket
      PolicyDocument:
        Statement:
          - Sid: PublicReadGetObject
            Effect: Deny
            Principal: '*'
            Action: 's3:GetObject'
            Resource: !Join ['', ['arn:aws:s3:::', !Ref S3Bucket, '/*']]
            Condition:
              - StringNotEquals: 
                  's3:x-amz-object-ownership': BucketOwnerEnforced
